services:
  redis:
    image: redis:alpine
    container_name: redis_kaskade
    command: redis-server --protected-mode no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kaskade-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_kaskade
    environment:
      # Correction ici : on pointe vers le nom du service 'redis'
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - kaskade-net

  db:
    image: postgres:15-alpine
    container_name: db_kaskade
    environment:
      - POSTGRES_USER=admin_kaskade
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=kaskade_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kaskade-net

networks:
  kaskade-net:
    driver: bridge

volumes:
  postgres_data: